### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by peter17**
Thanks!

### CODE REVIEW

**Comment by mvdbos** [comment]
@peter17 build is failing. Could you have a look and perhaps update your PR?

**Comment by peter17** [comment]
@mvdbos Sure! It seems it is linked to the signature of `vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/Configuration.php::getConfigTreeBuilder`
I updated this dependency as well to be compatible...

**Comment by mvdbos** [comment]
It still fails. Can you try again and test locally first with `bin/static-analysis` and `bin/coverage-enforce 100` scripts? If that succeeds, it should be fine. Note that it only fails on PHP 8.2 and not on 8.0 or 8.1.

**Comment by peter17** [comment]
@mvdbos It fails because of https://github.com/pdepend/pdepend/issues/695 

Let's just wait for the next release, then I will update this PR!

**Comment by mvdbos** [comment]
Thanks for the investigation so far!

Op zo 10 dec 2023 14:46 schreef Peter Potrowl ***@***.***>:

**Comment by peter17** [comment]
@mvdbos Should be good now! I ran `bin/static-analysis` and `bin/coverage-enforce 100` locally with PHP 8.2.13

**Comment by mvdbos** [comment]
Thanks @peter17

**Pull request merged**
